### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [cmerow/rangeModelMetadata#1]
Email April 1:

rangeModelMetadata has strong dependence on at least one of `rgdal`,
`rgeos` or `maptools`, but does not seem to use any functionality in code.
The usage may have been in `raster`, which now uses `terra` instead, or may
be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or
`maptools` to Suggests: and protect any use against these packages not
being present. The packages will be archived in October 2023. See
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and
perhaps view
https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_
YmAh4pq9&index=1.

Best wishes,

On Wed, 14 Dec 2022, Roger Bivand wrote:

> Dear Maintainer,
>
> rangeModelMetadata depends on (depends, imports or suggests) **raster**
> and one or more of the retiring packages **rgdal**, **rgeos** or
> **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since
> **raster** `3.6.3`, all use of external FOSS library functionality has
> been transferred to **terra**, making the retiring packages very likely
> redundant. It would help greatly if you could remove dependencies on the
> retiring packages as soon as possible.

Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

Removing retiring packages from DESCRIPTION, NAMESPACE and spurious roxygen tags, and running CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path gives this log:
[00check.log](https://github.com/cmerow/rangeModelMetadata/files/11352447/00check.log)

**Comment by rsbivand** [comment]
@cmerow See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by rsbivand** [comment]
@cmerow Less than three weeks remain to fix this. Can the switch_to_sf_and_terra branch be submitted in time?

**Comment by bmaitner** [comment]
@cmerow The pull request I submitted a while back should take care of the issues.  I've run all the devtools checks that I can (i.e., those that don't have to be run by the package maintainer), and everything checks out. So we should just be able to merge and then submit the updates to CRAN

**Comment by rsbivand** [comment]
Maybe run CMD check when the retiring packages have been removed, or are not on the library path.

**Comment by rsbivand** [comment]
@bmaitner @cmerow R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos. It remains the case that many packages importing the raster package needlessly depend on retiring packages, as raster stopped using them a year ago.

**Comment by rsbivand** [comment]
Thanks for your cooperation!
